defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: shredhub_development

test:
  <<: *defaults
  database: shredhub_test

# set these environment variables on your prod server
#production:
#  <<: *defaults
#  database: shredhub
#  username: <%= ENV['MONGO_USERNAME'] %>
#  password: <%= ENV['MONGO_PASSWORD'] %>
production:
    uri: <%= ENV['MONGOHQ_URL'] %>