paths:
  backbone : vendor/backbone
  underscore : vendor/underscore
  jquery : vendor/jquery
  marionette : vendor/backbone.marionette
  handlebars : vendor/handlebars
  text : vendor/text
  backbone.wreqr : vendor/backbone.wreqr
  backbone.babysitter : vendor/backbone.babysitter
  bootstrap : vendor/bootstrap.min
  panda: //cdn.pandastream.com/u/2.0/panda-uploader.min
shim:
  'underscore':
    exports: '_'
  'jquery': 
    exports : 'jQuery'
  'backbone':
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  'marionette':
    deps: ['jquery', 'underscore', 'jquery']
    exports: 'Marionette'
  'handlebars':
    deps: []
    exports: 'Handlebars'
  'bootstrap':
    deps: ['jquery']
    exports: 'Bootstrap'
  'panda' :
    exports : 'panda'

