modules:
  - name: 'application'

paths:
  backbone : vendor/backbone
  underscore : vendor/underscore
  jquery : vendor/jquery
  marionette : vendor/backbone.marionette
  handlebars : vendor/handlebars
  text : vendor/text
  backbone.wreqr : vendor/backbone.wreqr
  backbone.babysitter : vendor/backbone.babysitter
  bootstrap : vendor/bootstrap.min
shim:
  'underscore':
    exports: '_'
  'jquery':
    exports : 'jquery'
  'backbone':
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  'marionette':
    deps: ['jquery', 'underscore', 'backbone']
    exports: 'Marionette'
  'handlebars':
    deps: []
    exports: 'Handlebars'
  'bootstrap':
    deps: ['jquery']
    exports: 'Bootstrap'

